# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiplayerservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='multiplayerservice.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\035github.com/horahoradev/nexus2',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18multiplayerservice.proto\x12\x05proto\"\x94\x01\n\rClientMessage\x12$\n\x07movemsg\x18\x01 \x01(\x0b\x32\x11.proto.ClientMoveH\x00\x12,\n\x0bnavigatemsg\x18\x02 \x01(\x0b\x32\x15.proto.ClientNavigateH\x00\x12$\n\x07\x63hatmsg\x18\x03 \x01(\x0b\x32\x11.proto.ClientChatH\x00\x42\t\n\x07Payload\"\xbb\x01\n\rServerMessage\x12$\n\x07movemsg\x18\x01 \x01(\x0b\x32\x11.proto.ServerMoveH\x00\x12-\n\x0cnavigateresp\x18\x02 \x01(\x0b\x32\x15.proto.ServerNavigateH\x00\x12$\n\x07\x63hatmsg\x18\x03 \x01(\x0b\x32\x11.proto.ServerChatH\x00\x12$\n\x07joinmsg\x18\x04 \x01(\x0b\x32\x11.proto.PlayerJoinH\x00\x42\t\n\x07Payload\"\"\n\nClientMove\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"\x1f\n\x0e\x43lientNavigate\x12\r\n\x05mapID\x18\x01 \x01(\t\"\x1d\n\nClientChat\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\nServerMove\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x12\x12\n\nplayerUUID\x18\x03 \x01(\t\"V\n\x0eServerNavigate\x12\x0e\n\x06maploc\x18\x01 \x01(\t\x12\x10\n\x08\x61udioloc\x18\x02 \x01(\t\x12\"\n\x07players\x18\x03 \x03(\x0b\x32\x11.proto.PlayerJoin\"1\n\nServerChat\x12\x12\n\nplayerUUID\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\nPlayerJoin\x12\x11\n\tspriteloc\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x03\x12\t\n\x01y\x18\x03 \x01(\x03\x32O\n\x12MultiplayerService\x12\x39\n\x05Login\x12\x14.proto.ClientMessage\x1a\x14.proto.ServerMessage\"\x00(\x01\x30\x01\x42\x1fZ\x1dgithub.com/horahoradev/nexus2b\x06proto3'
)




_CLIENTMESSAGE = _descriptor.Descriptor(
  name='ClientMessage',
  full_name='proto.ClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movemsg', full_name='proto.ClientMessage.movemsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='navigatemsg', full_name='proto.ClientMessage.navigatemsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chatmsg', full_name='proto.ClientMessage.chatmsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Payload', full_name='proto.ClientMessage.Payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=36,
  serialized_end=184,
)


_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='proto.ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movemsg', full_name='proto.ServerMessage.movemsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='navigateresp', full_name='proto.ServerMessage.navigateresp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chatmsg', full_name='proto.ServerMessage.chatmsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joinmsg', full_name='proto.ServerMessage.joinmsg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Payload', full_name='proto.ServerMessage.Payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=187,
  serialized_end=374,
)


_CLIENTMOVE = _descriptor.Descriptor(
  name='ClientMove',
  full_name='proto.ClientMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.ClientMove.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.ClientMove.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=410,
)


_CLIENTNAVIGATE = _descriptor.Descriptor(
  name='ClientNavigate',
  full_name='proto.ClientNavigate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapID', full_name='proto.ClientNavigate.mapID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=443,
)


_CLIENTCHAT = _descriptor.Descriptor(
  name='ClientChat',
  full_name='proto.ClientChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.ClientChat.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=474,
)


_SERVERMOVE = _descriptor.Descriptor(
  name='ServerMove',
  full_name='proto.ServerMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.ServerMove.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.ServerMove.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerUUID', full_name='proto.ServerMove.playerUUID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=530,
)


_SERVERNAVIGATE = _descriptor.Descriptor(
  name='ServerNavigate',
  full_name='proto.ServerNavigate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='maploc', full_name='proto.ServerNavigate.maploc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audioloc', full_name='proto.ServerNavigate.audioloc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='players', full_name='proto.ServerNavigate.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=618,
)


_SERVERCHAT = _descriptor.Descriptor(
  name='ServerChat',
  full_name='proto.ServerChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerUUID', full_name='proto.ServerChat.playerUUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.ServerChat.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=669,
)


_PLAYERJOIN = _descriptor.Descriptor(
  name='PlayerJoin',
  full_name='proto.PlayerJoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spriteloc', full_name='proto.PlayerJoin.spriteloc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.PlayerJoin.x', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.PlayerJoin.y', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=671,
  serialized_end=724,
)

_CLIENTMESSAGE.fields_by_name['movemsg'].message_type = _CLIENTMOVE
_CLIENTMESSAGE.fields_by_name['navigatemsg'].message_type = _CLIENTNAVIGATE
_CLIENTMESSAGE.fields_by_name['chatmsg'].message_type = _CLIENTCHAT
_CLIENTMESSAGE.oneofs_by_name['Payload'].fields.append(
  _CLIENTMESSAGE.fields_by_name['movemsg'])
_CLIENTMESSAGE.fields_by_name['movemsg'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['Payload']
_CLIENTMESSAGE.oneofs_by_name['Payload'].fields.append(
  _CLIENTMESSAGE.fields_by_name['navigatemsg'])
_CLIENTMESSAGE.fields_by_name['navigatemsg'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['Payload']
_CLIENTMESSAGE.oneofs_by_name['Payload'].fields.append(
  _CLIENTMESSAGE.fields_by_name['chatmsg'])
_CLIENTMESSAGE.fields_by_name['chatmsg'].containing_oneof = _CLIENTMESSAGE.oneofs_by_name['Payload']
_SERVERMESSAGE.fields_by_name['movemsg'].message_type = _SERVERMOVE
_SERVERMESSAGE.fields_by_name['navigateresp'].message_type = _SERVERNAVIGATE
_SERVERMESSAGE.fields_by_name['chatmsg'].message_type = _SERVERCHAT
_SERVERMESSAGE.fields_by_name['joinmsg'].message_type = _PLAYERJOIN
_SERVERMESSAGE.oneofs_by_name['Payload'].fields.append(
  _SERVERMESSAGE.fields_by_name['movemsg'])
_SERVERMESSAGE.fields_by_name['movemsg'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['Payload']
_SERVERMESSAGE.oneofs_by_name['Payload'].fields.append(
  _SERVERMESSAGE.fields_by_name['navigateresp'])
_SERVERMESSAGE.fields_by_name['navigateresp'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['Payload']
_SERVERMESSAGE.oneofs_by_name['Payload'].fields.append(
  _SERVERMESSAGE.fields_by_name['chatmsg'])
_SERVERMESSAGE.fields_by_name['chatmsg'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['Payload']
_SERVERMESSAGE.oneofs_by_name['Payload'].fields.append(
  _SERVERMESSAGE.fields_by_name['joinmsg'])
_SERVERMESSAGE.fields_by_name['joinmsg'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['Payload']
_SERVERNAVIGATE.fields_by_name['players'].message_type = _PLAYERJOIN
DESCRIPTOR.message_types_by_name['ClientMessage'] = _CLIENTMESSAGE
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
DESCRIPTOR.message_types_by_name['ClientMove'] = _CLIENTMOVE
DESCRIPTOR.message_types_by_name['ClientNavigate'] = _CLIENTNAVIGATE
DESCRIPTOR.message_types_by_name['ClientChat'] = _CLIENTCHAT
DESCRIPTOR.message_types_by_name['ServerMove'] = _SERVERMOVE
DESCRIPTOR.message_types_by_name['ServerNavigate'] = _SERVERNAVIGATE
DESCRIPTOR.message_types_by_name['ServerChat'] = _SERVERCHAT
DESCRIPTOR.message_types_by_name['PlayerJoin'] = _PLAYERJOIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)

ClientMove = _reflection.GeneratedProtocolMessageType('ClientMove', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMOVE,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ClientMove)
  })
_sym_db.RegisterMessage(ClientMove)

ClientNavigate = _reflection.GeneratedProtocolMessageType('ClientNavigate', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTNAVIGATE,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ClientNavigate)
  })
_sym_db.RegisterMessage(ClientNavigate)

ClientChat = _reflection.GeneratedProtocolMessageType('ClientChat', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCHAT,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ClientChat)
  })
_sym_db.RegisterMessage(ClientChat)

ServerMove = _reflection.GeneratedProtocolMessageType('ServerMove', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMOVE,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ServerMove)
  })
_sym_db.RegisterMessage(ServerMove)

ServerNavigate = _reflection.GeneratedProtocolMessageType('ServerNavigate', (_message.Message,), {
  'DESCRIPTOR' : _SERVERNAVIGATE,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ServerNavigate)
  })
_sym_db.RegisterMessage(ServerNavigate)

ServerChat = _reflection.GeneratedProtocolMessageType('ServerChat', (_message.Message,), {
  'DESCRIPTOR' : _SERVERCHAT,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.ServerChat)
  })
_sym_db.RegisterMessage(ServerChat)

PlayerJoin = _reflection.GeneratedProtocolMessageType('PlayerJoin', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERJOIN,
  '__module__' : 'multiplayerservice_pb2'
  # @@protoc_insertion_point(class_scope:proto.PlayerJoin)
  })
_sym_db.RegisterMessage(PlayerJoin)


DESCRIPTOR._options = None

_MULTIPLAYERSERVICE = _descriptor.ServiceDescriptor(
  name='MultiplayerService',
  full_name='proto.MultiplayerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=726,
  serialized_end=805,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='proto.MultiplayerService.Login',
    index=0,
    containing_service=None,
    input_type=_CLIENTMESSAGE,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MULTIPLAYERSERVICE)

DESCRIPTOR.services_by_name['MultiplayerService'] = _MULTIPLAYERSERVICE

# @@protoc_insertion_point(module_scope)
